name: Test

on: 
  push:
    branches: main
    
  workflow_dispatch:

jobs:
  build: 
    runs-on: ubuntu-latest
    
    steps: 
      - uses: actions/chekout@v
      
      - name: Run a one-line script
        run: echo Hello World!!!
  
